export const ERROR = 'ERROR'

export const UNLOCK_ACCOUNT = 'UNLOCK_ACCOUNT'
export const LOCK_ACCOUNT = 'LOCK_ACCOUNT'
export const CREATE_ACCOUNT = 'CREATE_ACCOUNT'
export const SET_BALANCES = 'SET_BALANCES'

export const SET_CSDT = 'SET_CSDT'
export const SET_PENDING_CSDT = 'SET_PENDING_CSDT'
export const SET_CSDT_PARAMETERS = 'SET_CSDT_PARAMETERS'

export const SET_PRICES = 'SET_PRICES'
export const SET_INTEREST = 'SET_INTEREST'
export const SET_SUPPLY = 'SET_SUPPLY'
export const SET_STAKING = 'SET_STAKING'

export const SET_TOKENS = 'SET_TOKENS'

export const START_LOADER = 'START_LOADER'
export const STOP_LOADER = 'STOP_LOADER'

export const SET_NODE_INFO = 'SET_NODE_INFO'

export const SET_VALIDATORS = 'SET_VALIDATORS'
export const SET_UNBONDED_DELEGATIONS = 'SET_UNBONDED_DELEGATIONS'

export const SET_DELEGATIONS = 'SET_DELEGATIONS'
export const SET_BONDED_VALIDATORS = 'SET_BONDED_VALIDATORS'

export const SET_LIQUIDATIONS = 'SET_LIQUIDATIONS'
export const SET_DELEGATION_REWARDS = 'SET_DELEGATION_REWARDS'

export const SET_SYNTHETICS = 'SET_SYNTHETICS'

export const TOGGLE_ACCOUNT = 'TOGGLE_ACCOUNT'
export const COLLAPSE_ACCOUNT = 'COLLAPSE_ACCOUNT'
export const EXPAND_ACCOUNT = 'EXPAND_ACCOUNT'

export const SET_PROPOSALS = 'SET_PROPOSALS'
export const SET_PROPOSAL = 'SET_PROPOSAL'
